apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2020-07-20T00:37:55Z"
    labels:
      name: nginx
    name: nginx
    namespace: default
    resourceVersion: "6386"
    selfLink: /api/v1/namespaces/default/pods/nginx
    uid: cb7328b1-0091-42ec-a6cc-d5d3e4ad7185
  spec:
    containers:
    - image: hifrodo/nginx:v1
      imagePullPolicy: IfNotPresent
      name: nginx
      ports:
      - containerPort: 80
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-7w298
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: gke-my-first-cluster-1-default-pool-3f4dfe82-szdl
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
     operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: default-token-7w298
      secret:
        defaultMode: 420
        secretName: default-token-7w298
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2020-07-20T00:37:55Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2020-07-20T00:38:14Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2020-07-20T00:38:14Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2020-07-20T00:37:55Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://ca2dd985eaf49052fa16c886d39e10f80dbebab169cbe5ca98681d35865d9fe7
      image: hifrodo/nginx:v1
      imageID: docker-pullable://hifrodo/nginx@sha256:18edf1a360344f9751309ff76e1a3634ee6a7d56150ceb0922213c78fa75ce46
      lastState: {}
      name: nginx
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2020-07-20T00:38:13Z"
    hostIP: 10.128.0.2
    phase: Running
    podIP: 10.40.0.3
    podIPs:
    - ip: 10.40.0.3
    qosClass: BestEffort
    startTime: "2020-07-20T00:37:55Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""